version: '3'
services:
  express:
    build:
      context: .
      target: production
    container_name: express-container-prod
    # volumes:
    #   - ./index.js:./app/index.js:ro
    environment:
      - ENV=production
