version: '3'
services:
  express:
    image: younesshub/express
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - mongoDB
      - redisDB
  mongoDB:
    image: mongo
    restart: always
    volumes:
      - mongo-db-v:/data/db
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    container_name: mongodb-express-container
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://root:test@mongoDB:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongoDB

  redisDB:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    container_name: redis-container

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - express
volumes:
  mongo-db-v: